/*

 BACKGROUNDTWO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\dalle\Desktop\GB_Snake\backgrounds\Ground\Ground.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundTwoWidth 40
#define backgroundTwoHeight 18
#define backgroundTwoBank 0

extern unsigned char backgroundTwo[];

/* End of BACKGROUNDTWO.H */
