/*

 BACKGROUND-1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\dalle\Desktop\GB_Snake\backgrounds\Ground\Ground.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define background-1Width 40
#define background-1Height 18
#define background-1Bank 0

extern unsigned char background-1[];

/* End of BACKGROUND-1.H */
